version: "3.8"

services:
  django:
    container_name: django
    build: backend_py
    networks:
      - local
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME_PREFIX}_py
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend_py/student_voting_portal/:/app/student_voting_portal/
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
  spring-boot:
    container_name: spring-boot
    build: backend_java
    networks:
      - local
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME_PREFIX}_java
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend_java/src/:/app/src/
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
  react:
    container_name: react
    build: frontend
    networks:
      - local
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/package.json:/app/package.json
    ports:
      - 3000:3000
    depends_on:
      - django
      - spring-boot
  database:
    container_name: mysql
    image: mysql:8.0.33-debian
    platform: linux/amd64
    restart: always
    networks:
      - local
    environment:
      - MYSQL_DATABASE_PREFIX=${DB_NAME_PREFIX}
      - MYSQL_ROOT_PASSWORD=root_123
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_HOST=%
    volumes:
      - v_mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "24850:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s

networks:
  local:
    driver: bridge

volumes:
  v_mysql:
