# Generated by Django 4.2.1 on 2023-05-10 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_university"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="university",
            name="delete_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="delete_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
